spring.application.name=user-service
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#will disable before production deployment
spring.jpa.show-sql=true
logging.pattern.console=%d{HH:mm:ss.SSS} %5p [%X{requestId:-NO-REQ-ID}] [%t] %-40logger{39} : %m%n
jwt.secret=${JWT_SECRET:orderflow-super-secret-key-that-is-long-enough-for-hs256-algorithm}
jwt.expiration=${JWT_EXPIRATION:86400000}
spring.threads.virtual.enabled=true
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health